/*
 * JSP generated by Resin 2.1.8 (built Thu Mar  6 11:50:23 PST 2003)
 */

import javax.servlet.*;
import javax.servlet.jsp.*;
import javax.servlet.http.*;
import util.DebugUtil;

public class _header2__jsp extends com.caucho.jsp.JavaPage{
  private boolean _caucho_isDead;
  
  public void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response)
    throws java.io.IOException, javax.servlet.ServletException
  {
    com.caucho.jsp.QPageContext pageContext = (com.caucho.jsp.QPageContext) com.caucho.jsp.QJspFactory.create().getPageContext(this, request, response, null, true, 8192, true);
    javax.servlet.jsp.JspWriter out = (javax.servlet.jsp.JspWriter) pageContext.getOut();
    javax.servlet.ServletConfig config = getServletConfig();
    javax.servlet.Servlet page = this;
    javax.servlet.http.HttpSession session = pageContext.getSession();
    javax.servlet.ServletContext application = pageContext.getServletContext();
    response.setContentType("text/html");
    org.apache.struts.taglib.tiles.UseAttributeTag _jsp_tag0 = null;
    org.apache.struts.taglib.bean.WriteTag _jsp_tag1 = null;
    org.apache.struts.taglib.tiles.GetAttributeTag _jsp_tag2 = null;
    tilesapp.UserDomainObject user = null;
    try {
      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      pageContext.write(_jsp_string1, 0, _jsp_string1.length);
      pageContext.write(_jsp_string1, 0, _jsp_string1.length);
      pageContext.write(_jsp_string2, 0, _jsp_string2.length);
      if (_jsp_tag0 == null) {
        _jsp_tag0 = new org.apache.struts.taglib.tiles.UseAttributeTag();
        _jsp_tag0.setPageContext(pageContext);
        _jsp_tag0.setParent((javax.servlet.jsp.tagext.Tag) null);
        _jsp_tag0.setClassname("tilesapp.UserDomainObject");
        _jsp_tag0.setName("user");
        _jsp_tag0.setId("user");
      }

      _jsp_tag0.doStartTag();
      int _jsp_endTagVar3 = _jsp_tag0.doEndTag();
      if (_jsp_endTagVar3 == javax.servlet.jsp.tagext.Tag.SKIP_PAGE)
        return;
      user = (tilesapp.UserDomainObject)pageContext.findAttribute("user");
      pageContext.write(_jsp_string3, 0, _jsp_string3.length);
      if (_jsp_tag1 == null) {
        _jsp_tag1 = new org.apache.struts.taglib.bean.WriteTag();
        _jsp_tag1.setPageContext(pageContext);
        _jsp_tag1.setParent((javax.servlet.jsp.tagext.Tag) null);
        _jsp_tag1.setName("user");
      }

      _jsp_tag1.setProperty("userName");
      _jsp_tag1.doStartTag();
      pageContext.write(_jsp_string4, 0, _jsp_string4.length);
      if (_jsp_tag2 == null) {
        _jsp_tag2 = new org.apache.struts.taglib.tiles.GetAttributeTag();
        _jsp_tag2.setPageContext(pageContext);
        _jsp_tag2.setParent((javax.servlet.jsp.tagext.Tag) null);
        _jsp_tag2.setIgnore(true);
        _jsp_tag2.setName("title");
      }

      int _jsp_endTagVar10 = _jsp_tag2.doEndTag();
      if (_jsp_endTagVar10 == javax.servlet.jsp.tagext.Tag.SKIP_PAGE)
        return;
      pageContext.write(_jsp_string5, 0, _jsp_string5.length);
      _jsp_tag1.setProperty("firstName");
      _jsp_tag1.doStartTag();
      pageContext.write(_jsp_string6, 0, _jsp_string6.length);
      _jsp_tag1.setProperty("lastName");
      _jsp_tag1.doStartTag();
      pageContext.write(_jsp_string7, 0, _jsp_string7.length);
    } catch (java.lang.Throwable _jsp_e) {
      pageContext.handlePageException(_jsp_e);
    } finally {
      if (_jsp_tag0 != null)
        _jsp_tag0.release();
      if (_jsp_tag1 != null)
        _jsp_tag1.release();
      if (_jsp_tag2 != null)
        _jsp_tag2.release();
      JspFactory.getDefaultFactory().releasePageContext(pageContext);
    }
  }

  private com.caucho.java.LineMap _caucho_line_map;
  private java.util.ArrayList _caucho_depends = new java.util.ArrayList();

  public boolean _caucho_isModified()
  {
    if (_caucho_isDead)
      return true;
    if (com.caucho.util.CauchoSystem.getVersionId() != 2057024150)
      return true;
    for (int i = _caucho_depends.size() - 1; i >= 0; i--) {
      com.caucho.vfs.Depend depend;
      depend = (com.caucho.vfs.Depend) _caucho_depends.get(i);
      if (depend.isModified())
        return true;
    }
    return false;
  }

  public long _caucho_lastModified()
  {
    return 0;
  }

  public com.caucho.java.LineMap _caucho_getLineMap()
  {
    return _caucho_line_map;
  }

  public void destroy()
  {
      _caucho_isDead = true;
      super.destroy();
  }

  public void init(com.caucho.java.LineMap lineMap,
                   com.caucho.vfs.Path appDir)
    throws javax.servlet.ServletException
  {
    com.caucho.vfs.Path resinHome = com.caucho.util.CauchoSystem.getResinHome();
    com.caucho.vfs.MergePath mergePath = new com.caucho.vfs.MergePath();
    mergePath.addMergePath(appDir);
    mergePath.addMergePath(resinHome);
    mergePath.addClassPath(getClass().getClassLoader());
    _caucho_line_map = new com.caucho.java.LineMap("_header2__jsp.java", "/tileschap/header2.jsp");
    _caucho_line_map.add(5, 1);
    _caucho_line_map.add(3, 31);
    _caucho_line_map.add(11, 34);
    _caucho_line_map.add(11, 47);
    _caucho_line_map.add(22, 49);
    _caucho_line_map.add(33, 59);
    _caucho_line_map.add(43, 71);
    _caucho_line_map.add(44, 74);
    com.caucho.vfs.Depend depend;
    depend = new com.caucho.vfs.Depend(appDir.lookup("header2.jsp"), 1062892206000L, 1149L);
    _caucho_depends.add(depend);
  }

  private static byte []_jsp_string0;
  private static byte []_jsp_string4;
  private static byte []_jsp_string6;
  private static byte []_jsp_string7;
  private static byte []_jsp_string5;
  private static byte []_jsp_string3;
  private static byte []_jsp_string1;
  private static byte []_jsp_string2;
  static {
    _jsp_string0 = "\r\n<!--Header2.jsp Begin -->\r\n".getBytes();
    _jsp_string4 = "\r\n		  \r\n	   </font>\r\n	   </div>\r\n	   &nbsp;\r\n	</td>\r\n	\r\n	\r\n	<td width=\"33%\">\r\n	    &nbsp;\r\n	    <font color=\"#36566E\">\r\n	        ".getBytes();
    _jsp_string6 = " <br />\r\n		   ".getBytes();
    _jsp_string7 = " <br />\r\n		   </blockquote>\r\n	   </font>\r\n	   </div>\r\n	   &nbsp;\r\n	</td>\r\n</tr>\r\n</table>\r\n</center>\r\n<!--Header2.jsp END -->".getBytes();
    _jsp_string5 = "\r\n	    </font>    	\r\n	    &nbsp;\r\n	</td>\r\n	\r\n	<td width=\"33%\" bgcolor=\"#36566E\">\r\n	   &nbsp;\r\n	   <div align='left'>\r\n	   <font size=\"1\" color=\"white\">\r\n	       <blockquote>\r\n		   ".getBytes();
    _jsp_string3 = "\r\n\r\n	<td width=\"33%\" bgcolor=\"#36566E\">\r\n	  &nbsp;\r\n	   <div align='left'>\r\n	   <font size=\"1\" color=\"orange\">\r\n		   \r\n		   currently logged in as \r\n		   ".getBytes();
    _jsp_string1 = "\r\n".getBytes();
    _jsp_string2 = "\r\n<center>\r\n<table>\r\n<tr>\r\n\r\n\r\n".getBytes();
  }
}
